[package]
name = "weight_stats"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.7.4", features = ["integer", "x86_64-unix" ] }
bincode = "1.3.3"

[profile.devo]
inherits = "dev"
opt-level = 3
lto = "off"
debug-assertions = false

#aarch64-unix
#x86_64-unix
