name: iOS App tests

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ios:
    name: Build For iOS on macOS
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Install latest stable
        uses: dtolnay/rust-toolchain@315e265cd78dad1e1dcf3a5074f6d6c47029d5aa
        with:
          toolchain: stable

      - name: Install Swift Rust targets
        run: |
          ./setup_tfhe_xcframework.sh

  build-server:
    name: Build server docker
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Setup docker build config
        run: |
          cd Server
          source .common_env

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          context: Server
          file: Server/Dockerfile.server
          tags: zama-ios-apps:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

test-python-modules:
  name: Test Python Modules on ${{ matrix.python-version }}
  runs-on: ubuntu-latest

  strategy:
    matrix:
      python-version: ["3.10"] # ["3.8", "3.9", , "3.11", "3.12"]

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install maturin pytest numpy

    - name: Build and install all Python modules
      run: |
        maturin develop --release --manifest-path tasks/sleep_quality/Cargo.toml
        maturin develop --release --manifest-path tasks/weight_stats/Cargo.toml

    - name: Run all Python tests
      run: pytest tests/
